services:
  - type: web
    name: fastapi-on-render
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:main --host 0.0.0.0 --port 8000"
    autoDeploy: true
